<?php

/** Payment Gateways */
const GATEWAY_EKPAY = 'EKPAY';
const GATEWAY_SSLCOMMERZ = 'SSLCOMMERZ';
const GATEWAY_BKASH = 'BKASH';
const GATEWAY_NAGAD = 'NAGAD';
const GATEWAY_PORTWALLET = 'PORTWALLET';
const GATEWAY_SHURJOPAY = 'SHURJOPAY';
const GATEWAY_AAMARPAY = 'AAMARPAY';
const GATEWAY_2CHECKOUT = '2CHECKOUT';
const GATEWAY_AUTHORIZEDOTNET = 'AUTHORIZEDOTNET';
const GATEWAY_STRIPE = 'STRIPE';
const GATEWAY_PAYPAL = 'PAYPAL';

/** Payment Purposes */
const PURPOSE_COURSE_ENROLLMENT = 'COURSE_ENROLLMENT';
const PURPOSE_ASSOCIATION_MEMBERSHIP = 'ASSOCIATION_MEMBERSHIP';
const PURPOSE_RPL_CERTIFICATION_APPLICATION = 'RPL_CERTIFICATION_APPLICATION';
const PURPOSE_RTO_TO_BTEB = 'RTO_TO_BTEB';


return [
    'all_payment_gateways' => [
        GATEWAY_EKPAY => 'Ekpay',
        GATEWAY_SSLCOMMERZ => 'SSLCOMMERZ',
        GATEWAY_BKASH => 'bKash',
        GATEWAY_NAGAD => 'Nagad',
        GATEWAY_PORTWALLET => 'PortWallet',
        GATEWAY_SHURJOPAY => 'ShurjaPay',
        GATEWAY_AAMARPAY => 'Aamarpay',
        GATEWAY_2CHECKOUT => '2Checkout',
        GATEWAY_AUTHORIZEDOTNET => 'Authorize.net',
        GATEWAY_STRIPE => 'Stripe',
        GATEWAY_PAYPAL => 'Paypal'
    ],
    'all_payment_purposes' => [
        PURPOSE_COURSE_ENROLLMENT,
        PURPOSE_ASSOCIATION_MEMBERSHIP,
        PURPOSE_RPL_CERTIFICATION_APPLICATION,
        PURPOSE_RTO_TO_BTEB,
    ]
];
